// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMhik-2XDFqEH649gAMvJzGA02-G-ylMs',
    appId: '1:23113216848:web:4c4a622275b394a28c7255',
    messagingSenderId: '23113216848',
    projectId: 'fooddeliveryapp-92b82',
    authDomain: 'fooddeliveryapp-92b82.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-92b82.appspot.com',
    measurementId: 'G-B4LN2WPNV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQHYWH4QolkG3jKZe2L1VkTCSRFCkqYp4',
    appId: '1:23113216848:android:ddecdb60b16bde508c7255',
    messagingSenderId: '23113216848',
    projectId: 'fooddeliveryapp-92b82',
    storageBucket: 'fooddeliveryapp-92b82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWxD3rbwc6PHha1G45EgIQQnQ1GRzfSo0',
    appId: '1:23113216848:ios:69182ef1ef6bb1fe8c7255',
    messagingSenderId: '23113216848',
    projectId: 'fooddeliveryapp-92b82',
    storageBucket: 'fooddeliveryapp-92b82.appspot.com',
    iosBundleId: 'com.ecommerce.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWxD3rbwc6PHha1G45EgIQQnQ1GRzfSo0',
    appId: '1:23113216848:ios:5f5db5b59c90fc758c7255',
    messagingSenderId: '23113216848',
    projectId: 'fooddeliveryapp-92b82',
    storageBucket: 'fooddeliveryapp-92b82.appspot.com',
    iosBundleId: 'com.ecommerce.eCommerce.RunnerTests',
  );
}
